org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.218
neo_version_range=[21.1.218,)

# Loader
loader_version_range=[1,)

# Mod
mod_id=craftersgacha
mod_name=Crafters Gacha
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=org.crafterscr
mod_authors=Crafters CR
mod_description=Sistema server-side de gachas configurable para Minecraft.